language: c

cache: ccache

cache:
  directories:
    - .cache

matrix:
  include:
    - os: linux
      env: CHANNEL=stable
      compiler: gcc

    - os: linux
      env: CHANNEL=devel
      compiler: gcc

  allow_failures:
    - env: CHANNEL=devel

  fast_finish: true

install:
  - export CHOOSENIM_NO_ANALYTICS=1
  - curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
  - sh init.sh -y
  - export PATH=~/.nimble/bin:$PATH
  - choosenim $CHANNEL

script:
  - nimble refresh
  - nimble build

branches:
  only:
    - master
    # Tags
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
